name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt install -y doxygen

    - name: Install Graphviz
      run: sudo apt install -y graphviz

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: List files for debugging
      run: ls -R ./docs/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
