name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: |
        curl -L -o doxygen.zip https://www.doxygen.nl/files/doxygen-1.9.3.windows.bin.zip
        tar -xf doxygen.zip -C doxygen
        setx PATH "%PATH%;%cd%\\doxygen\\doxygen-1.9.3\\bin"

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: List files for debugging
      run: |
        ls -R

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
