name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz

      - name: Build and deploy
        run: |
          doxygen Doxyfile
          cp -r docs/html/* $GITHUB_WORKSPACE
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
