name: Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt install -y doxygen && doxygen --version

    - name: Install Graphviz
      run: sudo apt install -y graphviz

    - name: Create documentation
      run: doxygen

    - name: List files for debugging
      run: ls -R ./html

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ./html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
